# Generated by Django 4.1.7 on 2023-04-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="facilitator",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
